# 基础信息配置
spring:
  application:
    name: wandaph-filetransfer
  datasource:
    url: jdbc:mysql://10.214.180.75:3306/loanpublic?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    password: nU/uN28/NiMYhVYOKsJoCv+/42Si2amixYlgBKsDyew1KmWMmC1ksk6yAiRQgzoJUhH0WPEHkx5WSvcpg9cQ4Q==
    username: loan
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

###################### Druid配置#################################
    #通过 http://domain:port/druid/login.html 访问druid监控页面
    initialSize: 5    #初始化时建立物理连接的个数
    maxActive: 20     #最大连接池数量
    minIdle: 5        #最小连接池数量
    maxWait: 60000    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL     #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true   #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效.建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false   #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    filters: stat,wall,log4j,config    #配置监控统计拦截的filters，去掉后监控界面sql无法统计.属性类型是字符串，常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
    logSlowSql: true
    connectionProperties: config.decrypt=true

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9016
#文件传输配置
fileService:
  fileUrl: http://10.214.179.181/attachFile
  rootDir: /cssdata/
  fileType: txt,png,PNG,jpg,JPG,jpeg,gif,GIF,html,xls,xlsx,pdf,doc,docx
  fileSize: 104857600
#日志配置
logging:
  config:  classpath:log/logback-spring.xml
#万达贷文件传输公钥和渠道号数组
filetransferConfig:
  filetransfer[0]:
    channel: CHN_WDD_0001
    publickey: MIICvDCCAiWgAwIBAgIJAJQSnqLIzMV2MA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJTSDELMAkGA1UEBwwCU0gxDjAMBgNVBAoMBVdhbmRhMREwDwYDVQQLDAhXYW5kYURhaTENMAsGA1UEAwwEV0RYRDEcMBoGCSqGSIb3DQEJARYNV0RYREBXYW5kYS5jbjAeFw0xODA4MTUwODUwMDBaFw00NTEyMzAwODUwMDBaMHcxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJTSDELMAkGA1UEBwwCU0gxDjAMBgNVBAoMBVdhbmRhMREwDwYDVQQLDAhXYW5kYURhaTENMAsGA1UEAwwEV0RYRDEcMBoGCSqGSIb3DQEJARYNV0RYREBXYW5kYS5jbjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAxGlbNSRCQfxASx/cBwiUbtAQNxRbCsbDrg13Ap3BK3f7XTC30oPQZE7GOJvHYldD7/frTas8M1LDEgqzhel9RBgkwAf9dydpcZufFKrHWWH1/23GKn77je7GK/MB/7lhHS2v4H4gPU5avy2AlI1IMRwX/EWQJdjIX+FyVQqWgrcCAwEAAaNQME4wHQYDVR0OBBYEFCT37mdcn5sHwyxSSkQ05XvcRGSbMB8GA1UdIwQYMBaAFCT37mdcn5sHwyxSSkQ05XvcRGSbMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEAGf8b06xnLFFwBbMH45ofSa/Ltuf//mth14DptJYAKCAg822yqC9awMYWdX9w5pEAE+jb/WtWcre30Gq5BRO+G12viN1XiQuCpaqZ7KJc6MtM+HI5wjStTikk8stLJbrc42XulnAo3zTzKsKk+WnQVcDOlawAqm2NtaklWwF5qbQ=
#MQ producer
hsjry:
  mq:
    namesrvAddr:  10.214.179.124:9876;10.214.179.125:9876
    contracttransfer:
      group:  wdd_contract_file
      topic:  wdd_contract_file
      tags: 952
consume:
  thread:
    max:
      mums: 30
