# 基础信息配置
spring:
  application:
    name: wandaph-filetransfer
  datasource:
    url: jdbc:mysql://10.53.156.240:3306/loanpublic?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    password: wdphdev2018
    username: dev
    driver-class-name: com.mysql.jdbc.Driver
    maximumPoolSize: 20
    connectionTimeout: 30000
    pool-prepared-statements: true
    max-open-prepared-statements: 250
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9016
#文件传输配置
fileService:
  fileUrl: http://10.214.179.181/attachFile
  rootDir: /cssdata/
  fileType: txt,png,PNG,jpg,JPG,jpeg,gif,GIF,html,xls,xlsx,pdf,doc,docx
  fileSize: 104857600
#日志配置
logging:
  config:  classpath:log/logback-spring.xml
#万达贷文件传输公钥和渠道号
filetransfer:
  wdd:
    channel: CHN_WDD_0001
    chn_wdd_0001_publickey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvppjMwFkHYnA3dkVa1xQtIojSdFpGZQ1eu79f
             5DXCne3e62KwPyeqJGy0eGMLHpsnO9cwDCPM4gco5DBLJa2vyByT/OC/RAED9WKFS+bYjJgZQXr7
             AoI16HobjifsiPT7zVCShg7dl/bD0baT1FMpf3EjjV+RFHb9HdSUdhnWgwIDAQAB
#MQ producer
hsjry:
  mq:
    namesrvAddr:  10.214.179.124:9876;10.214.179.125:9876
    contracttransfer:
      group:  wdd_contract_file
      topic:  wdd_contract_file
      tags: 952
consume:
  thread:
    max:
      mums: 30
